spring:
  jpa:
    database: postgresql
    hibernate.dialect: org.hibernate.dialect.PostgresQSLDialect
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
    show-sql: true

  datasource:
    hikari.maximum-pool-size: 4
    url: jdbc:postgresql://localhost:5432/sns
    platform: postgres
    username:
    password:
  redis:
    url: redis://localhost:6379
jwt:
  secret-key: fast_campus.sns-application-2023.secret_key
  # 30 days
  token.expired-time-ms: 2592000000
